/**
 * Data integrity sweep over every bundled puzzle.
 *
 * The single most valuable test in the project: the puzzle set is generated by
 * a script that talks to a 6-million-row external database, and a subtly wrong
 * filter or an off-by-one in the move convention would ship thousands of
 * unsolvable puzzles that no unit test of the UI would ever catch.
 *
 * Every puzzle is replayed through the real rules engine.
 */

import { test, describe, before } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Chess } from '../vendor/chess.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const readJson = (p) => JSON.parse(fs.readFileSync(path.join(ROOT, p), 'utf8'));

let index;
let shards;
let daily;

before(() => {
  index = readJson('data/index.json');
  shards = index.tiers.map((t) => readJson(t.file));
  daily = readJson('data/daily.json');
});

/** Replays a puzzle, returning a problem description or null if it is sound. */
function validate({ id, fen, moves, themes }) {
  const game = new Chess();
  try {
    game.load(fen);
  } catch (err) {
    return `${id}: bad FEN (${err.message})`;
  }

  const plies = moves.split(' ').filter(Boolean);
  if (plies.length < 2) return `${id}: needs at least an opponent move and a reply`;
  if (plies.length % 2 !== 0) return `${id}: line ends on the opponent's move`;

  for (const [i, uci] of plies.entries()) {
    const move = { from: uci.slice(0, 2), to: uci.slice(2, 4) };
    if (uci.length > 4) move.promotion = uci[4];
    try {
      const played = game.move(move);
      if (!played) return `${id}: ply ${i} (${uci}) is not legal`;
    } catch {
      return `${id}: ply ${i} (${uci}) is not legal`;
    }
  }

  // A mateInN puzzle must actually end in mate, or the promise is broken.
  const mateTag = themes.find((t) => /^mateIn\d$/.test(t));
  if (mateTag && !game.isCheckmate()) return `${id}: tagged ${mateTag} but does not end in checkmate`;
  if (mateTag) {
    const claimed = Number(mateTag.slice(6));
    const actual = (plies.length - 1 + 1) / 2; // player moves in the line
    if (actual !== claimed) return `${id}: tagged ${mateTag} but the line has ${actual} player moves`;
  }
  return null;
}

describe('bundled puzzle data', () => {
  test('index describes every shard', () => {
    assert.ok(index.total > 1000, `expected a substantial set, got ${index.total}`);
    assert.equal(index.tiers.length, 5);
    const counted = shards.reduce((n, s) => n + s.p.length, 0);
    assert.equal(counted, index.total, 'index total disagrees with the shards');
  });

  test('every puzzle in every tier is legal and sound', () => {
    const problems = [];
    for (const shard of shards) {
      for (const row of shard.p) {
        const [id, fen, moves, , themeIdx] = row;
        const themes = themeIdx.map((i) => shard.themes[i]);
        const problem = validate({ id, fen, moves, themes });
        if (problem) problems.push(problem);
      }
    }
    assert.deepEqual(problems.slice(0, 10), [], `${problems.length} invalid puzzles`);
  });

  test('every daily puzzle is legal and sound', () => {
    const problems = [];
    for (const [id, fen, moves, , themes] of daily.p) {
      const problem = validate({ id, fen, moves, themes: themes || [] });
      if (problem) problems.push(problem);
    }
    assert.deepEqual(problems.slice(0, 10), [], `${problems.length} invalid daily puzzles`);
  });

  test('the daily pool holds more than a year of puzzles', () => {
    assert.ok(daily.p.length >= 366, `only ${daily.p.length} daily puzzles`);
  });

  test('puzzle ids are unique within each shard', () => {
    for (const shard of shards) {
      const ids = shard.p.map((r) => r[0]);
      assert.equal(new Set(ids).size, ids.length, `tier ${shard.tier} has duplicate ids`);
    }
  });

  test('positions are sparse enough to feel "pocket"', () => {
    for (const shard of shards) {
      for (const row of shard.p) {
        const board = row[1].slice(0, row[1].indexOf(' '));
        const pieces = board.replace(/[^a-zA-Z]/g, '').length;
        assert.ok(pieces <= 14, `${row[0]} has ${pieces} pieces`);
      }
    }
  });

  test('ratings fall inside their tier band', () => {
    for (const [i, shard] of shards.entries()) {
      const [min, max] = index.tiers[i].rating;
      for (const row of shard.p) {
        assert.ok(row[3] >= min && row[3] <= max, `${row[0]} rated ${row[3]} is not in ${min}-${max}`);
      }
    }
  });

  test('every advertised drill theme has enough puzzles to drill', () => {
    const counts = {};
    for (const shard of shards) {
      for (const row of shard.p) {
        for (const i of row[4]) {
          const name = shard.themes[i];
          counts[name] = (counts[name] || 0) + 1;
        }
      }
    }
    for (const [theme, advertised] of Object.entries(index.themes)) {
      assert.equal(counts[theme], advertised, `index claims ${advertised} ${theme} puzzles`);
      assert.ok(advertised >= 12, `${theme} has only ${advertised} puzzles`);
    }
  });
});
