/**
 * The bundled piece sprite and its attribution.
 *
 * assets/pieces.svg is generated by tools/fetch-pieces.mjs from six upstream
 * projects, each with its own quirks. These tests pin the properties that,
 * if broken, would either render pieces invisibly or breach a licence.
 */

import { test, describe, before } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PIECE_SETS, DEFAULT_SET } from '../js/ui/pieces.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const TYPES = ['k', 'q', 'r', 'b', 'n', 'p'];
const COLOURS = ['w', 'b'];

/** Sets that live in the sprite file; Pocket is defined inline in pieces.js. */
const EXTERNAL = PIECE_SETS.filter((s) => s.id !== 'pocket');

let sprite;
let credits;
let symbols;

before(() => {
  sprite = fs.readFileSync(path.join(ROOT, 'assets/pieces.svg'), 'utf8');
  credits = fs.readFileSync(path.join(ROOT, 'assets/pieces/CREDITS.md'), 'utf8');
  symbols = [...sprite.matchAll(/<symbol\s+id="([^"]+)"([^>]*)>/g)]
    .map(([, id, attrs]) => ({ id, attrs }));
});

describe('piece sprite', () => {
  test('every external set contributes all 12 pieces', () => {
    const ids = new Set(symbols.map((s) => s.id));
    const missing = [];
    for (const set of EXTERNAL) {
      for (const colour of COLOURS) {
        for (const type of TYPES) {
          const id = `${set.id}-${colour}${type}`;
          if (!ids.has(id)) missing.push(id);
        }
      }
    }
    assert.deepEqual(missing, [], 'missing symbols');
    assert.equal(symbols.length, EXTERNAL.length * 12);
  });

  test('every symbol declares a viewBox', () => {
    // kiwen-suwi and cburnett ship no viewBox upstream — the generator
    // synthesises one from width/height. Without it a <symbol> does not scale
    // and the piece renders at raw pixel size instead of filling its square.
    const without = symbols.filter((s) => !/viewBox="[^"]+"/.test(s.attrs)).map((s) => s.id);
    assert.deepEqual(without, [], 'symbols missing a viewBox');
  });

  test('every viewBox is square and non-degenerate', () => {
    for (const s of symbols) {
      const vb = /viewBox="([^"]+)"/.exec(s.attrs)[1].trim().split(/[\s,]+/).map(Number);
      assert.equal(vb.length, 4, `${s.id}: malformed viewBox`);
      const [, , w, h] = vb;
      assert.ok(w > 0 && h > 0, `${s.id}: zero-sized viewBox`);
      // Non-square would distort, since pieceElement renders into a 45x45 box.
      assert.ok(Math.abs(w - h) / Math.max(w, h) < 0.02, `${s.id}: viewBox is not square (${w}x${h})`);
    }
  });

  test('the sprite carries no CSS that could leak between sets', () => {
    // rhosgfx ships <style>.cls-2{...}</style> per file, and .cls-2 means a
    // different colour in different pieces. Merged into one document those
    // rules would recolour other sets, so the generator inlines them away.
    assert.equal(/<style\b/i.test(sprite), false, 'sprite contains a <style> block');
    assert.equal(/\sclass\s*=/i.test(sprite), false, 'sprite contains a class attribute');
  });

  test('rhosgfx kept distinct light and dark palettes through inlining', () => {
    const fillsFor = (id) => {
      const m = new RegExp(`<symbol id="${id}"[^>]*>([\\s\\S]*?)</symbol>`).exec(sprite);
      assert.ok(m, `${id} not found`);
      return new Set([...m[1].matchAll(/fill:\s*(#[0-9a-fA-F]{3,6})/g)].map((x) => x[1].toLowerCase()));
    };
    const light = fillsFor('rhosgfx-wk');
    const dark = fillsFor('rhosgfx-bk');
    assert.ok(light.size > 1 && dark.size > 1, 'expected several fills per piece');
    // If class collisions had won, both kings would share one palette.
    const shared = [...light].filter((c) => dark.has(c));
    assert.ok(shared.length < light.size, 'white and black kings ended up identically coloured');
  });

  test('no id appears twice anywhere in the sprite', () => {
    // Upstream files are standalone documents that reuse short ids: all twelve
    // kiwen-suwi pieces defined <clipPath id="a">, and papercut repeated
    // gradient and filter ids. Merged into one sprite, every url(#a) resolved
    // to the first match and clipped eleven pieces into nothing — while still
    // reporting a valid getBBox(), so only a screenshot caught it.
    const ids = [...sprite.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]);
    const seen = new Set();
    const dupes = new Set();
    for (const id of ids) {
      if (seen.has(id)) dupes.add(id);
      seen.add(id);
    }
    assert.deepEqual([...dupes], [], 'duplicate ids collide across symbols');
  });

  test('every internal reference resolves inside the sprite', () => {
    const ids = new Set([...sprite.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]));
    const refs = new Set([
      ...[...sprite.matchAll(/url\(["']?#([^)"']+)["']?\)/g)].map((m) => m[1]),
      ...[...sprite.matchAll(/href="#([^"]+)"/g)].map((m) => m[1]),
    ]);
    const dangling = [...refs].filter((r) => !ids.has(r));
    assert.deepEqual(dangling, [], 'references point at ids that do not exist');
  });

  test('internal ids are namespaced to their own symbol', () => {
    for (const s of symbols) {
      const block = new RegExp(`<symbol id="${s.id}"[^>]*>([\\s\\S]*?)</symbol>`).exec(sprite)[1];
      const inner = [...block.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]);
      const unscoped = inner.filter((id) => !id.startsWith(`${s.id}-`));
      assert.deepEqual(unscoped, [], `${s.id} has ids outside its namespace`);
    }
  });

  test('the default set exists and is bundled', () => {
    assert.ok(PIECE_SETS.some((s) => s.id === DEFAULT_SET));
    assert.ok(sprite.includes(`id="${DEFAULT_SET}-wk"`));
  });
});

describe('attribution', () => {
  test('CREDITS names every external set with author and licence', () => {
    for (const set of EXTERNAL) {
      assert.ok(credits.includes(set.name), `CREDITS is missing ${set.name}`);
      assert.ok(credits.includes(set.author), `CREDITS is missing author ${set.author}`);
      assert.ok(credits.includes(set.licence), `CREDITS is missing licence ${set.licence}`);
    }
  });

  test('every bundled set carries a licence we can actually ship', () => {
    // Anything copyleft or NonCommercial would be incompatible with this
    // MIT-licensed project served publicly.
    const allowed = new Set(['BSD 3-clause', 'Apache 2.0', 'CC0 1.0', 'CC BY 4.0', 'MIT']);
    for (const set of PIECE_SETS) {
      assert.ok(allowed.has(set.licence), `${set.name} has unshippable licence "${set.licence}"`);
    }
  });

  test('the CC BY sets are recorded, since attribution is mandatory for them', () => {
    const ccby = PIECE_SETS.filter((s) => s.licence === 'CC BY 4.0');
    assert.ok(ccby.length > 0);
    for (const s of ccby) {
      assert.ok(credits.includes(s.author), `${s.name} requires attribution but is not credited`);
    }
  });

  test('the sprite is precached and the cache version was bumped past v1', () => {
    const sw = fs.readFileSync(path.join(ROOT, 'sw.js'), 'utf8');
    assert.ok(sw.includes("'assets/pieces.svg'"), 'sprite is not in the precache list');
    const version = /CACHE_VERSION\s*=\s*'([^']+)'/.exec(sw)[1];
    assert.notEqual(version, 'pocket-chess-v1', 'cache version must change or installs keep the old cache');
  });
});
