/**
 * Chess piece artwork.
 *
 * Seven sets. Six are externally sourced and bundled in `assets/pieces.svg`
 * (generated by tools/fetch-pieces.mjs); the seventh, "Pocket", was drawn for
 * this project and is defined inline below.
 *
 * All six external sets are permissively licensed — see assets/pieces/CREDITS.md
 * for authors and terms. Cburnett in particular is taken from Wikimedia Commons
 * under its BSD 3-clause option rather than from Lichess, which redistributes
 * the same artwork under GPLv2+.
 *
 * Pocket is kept for two reasons beyond taste: it is available before the
 * sprite file loads, and it is the only set whose colours come from CSS custom
 * properties, so it is the one that follows board themes and the high-contrast
 * accessibility theme. External sets have their colours baked in.
 *
 * Symbol ids are `<set>-<colour><type>`, e.g. `#cburnett-wn`. Pocket's shapes
 * sit on a 45x45 grid with the baseline at y=41 so all six pieces share a footing.
 */

import { getProfile } from '../core/store.js';

export const DEFAULT_SET = 'cburnett';

/**
 * Bundled sets, in the order they appear in Settings.
 * `themeable` marks the set whose colours follow the board theme.
 */
export const PIECE_SETS = [
  {
    id: 'cburnett', name: 'Cburnett', author: 'Colin M.L. Burnett',
    licence: 'BSD 3-clause', blurb: 'The classic Staunton set',
  },
  {
    id: 'pocket', name: 'Pocket', author: 'Drawn for this project',
    licence: 'MIT', blurb: 'Minimal — follows the board theme', themeable: true,
  },
  {
    id: 'chessnut', name: 'Chessnut', author: 'Alexis Luengas',
    licence: 'Apache 2.0', blurb: 'Clean and modern',
  },
  {
    id: 'rhosgfx', name: 'Vector Ranks', author: 'RhosGFX',
    licence: 'CC0 1.0', blurb: 'Warm flat vectors',
  },
  {
    id: 'kiwen-suwi', name: 'Kiwen Suwi', author: 'neverRare',
    licence: 'CC BY 4.0', blurb: 'Soft and rounded',
  },
  {
    id: 'totoy', name: 'Totoy', author: 'Kosal Sen',
    licence: 'CC BY 4.0', blurb: 'Playful and bold',
  },
  {
    id: 'papercut', name: 'Papercut', author: 'Nikolay Anzarov',
    licence: 'CC BY 4.0', blurb: 'Layered paper craft',
  },
];

export function setById(id) {
  return PIECE_SETS.find((s) => s.id === id) || PIECE_SETS.find((s) => s.id === DEFAULT_SET);
}

// -- the inline "Pocket" set -------------------------------------------------

const POCKET_SHAPES = {
  k: `
    <rect x="20.9" y="3" width="3.2" height="11" rx="1.6"/>
    <rect x="17.4" y="6.6" width="10.2" height="3.2" rx="1.6"/>
    <path d="M22.5 14.6c-6.4 0-11.6 4.3-11.6 9.6 0 3.3 1.7 5.4 3.4 7.1h16.4c1.7-1.7 3.4-3.8 3.4-7.1 0-5.3-5.2-9.6-11.6-9.6z"/>
    <rect x="11.6" y="30.6" width="21.8" height="4" rx="2"/>
    <rect x="8.4" y="36.6" width="28.2" height="4.6" rx="2.3"/>`,

  q: `
    <circle cx="6.4" cy="10.6" r="2.7"/>
    <circle cx="14.4" cy="8.2" r="2.7"/>
    <circle cx="22.5" cy="7.2" r="2.9"/>
    <circle cx="30.6" cy="8.2" r="2.7"/>
    <circle cx="38.6" cy="10.6" r="2.7"/>
    <path d="M6.4 11.4 10 30.2h25L38.6 11.4 31 19.9l-4.3-9.6-4.2 9.2-4.2-9.2-4.3 9.6z"/>
    <rect x="10.4" y="30.8" width="24.2" height="3.9" rx="1.9"/>
    <rect x="8.4" y="36.6" width="28.2" height="4.6" rx="2.3"/>`,

  r: `
    <path d="M10.6 8.4h6.1v3.9h4.1V8.4h5.5v3.9h4.1V8.4h6.1v9.9l-3.2 2.6v11.2l3.2 2.6v2.1H10.6v-2.1l3.2-2.6V20.9l-3.2-2.6z"/>
    <rect x="8.4" y="36.6" width="28.2" height="4.6" rx="2.3"/>`,

  b: `
    <circle cx="22.5" cy="7.4" r="2.9"/>
    <path d="M22.5 10.2c-4.9 3.4-8.6 8.2-8.6 13.4 0 3.9 2.4 6.9 5.4 8.6h6.4c3-1.7 5.4-4.7 5.4-8.6 0-5.2-3.7-10-8.6-13.4z"/>
    <rect x="13.6" y="31.2" width="17.8" height="3.7" rx="1.8"/>
    <rect x="8.4" y="36.6" width="28.2" height="4.6" rx="2.3"/>`,

  n: `
    <path d="M23.4 5.6c-1.4 0-2.6.7-3.3 1.9l-1.3 2.1-4 1.7c-2.9 1.2-5 3.9-5.6 7l-.8 4.6c-.3 1.6 1 3 2.6 3 .9 0 1.7-.5 2.2-1.2l2-3 2.6 1-3.6 4.9c-2.1 2.9-3.3 6.4-3.3 10v2.3h23.4v-7.1c0-10.6-4.7-19.9-10.6-25.3-.7-.6-1.5-.9-2.3-.9z"/>
    <rect x="8.4" y="36.6" width="28.2" height="4.6" rx="2.3"/>`,

  p: `
    <circle cx="22.5" cy="13.4" r="6.6"/>
    <path d="M22.5 19.2c-4.1 0-7.2 2.4-7.2 5.4 0 2 1.3 3.4 2.7 4.3-3.4 2.3-5.8 5.2-6.6 9.4h22.2c-.8-4.2-3.2-7.1-6.6-9.4 1.4-.9 2.7-2.3 2.7-4.3 0-3-3.1-5.4-7.2-5.4z"/>
    <rect x="9.4" y="36.6" width="26.2" height="4.6" rx="2.3"/>`,
};

function pocketSprite() {
  const symbols = [];
  for (const [type, shape] of Object.entries(POCKET_SHAPES)) {
    for (const colour of ['w', 'b']) {
      symbols.push(
        `<symbol id="pocket-${colour}${type}" viewBox="0 0 45 45">` +
          `<g class="pc pc-${colour}">${shape}</g>` +
        `</symbol>`
      );
    }
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" style="position:absolute;width:0;height:0;overflow:hidden">${symbols.join('')}</svg>`;
}

// -- active set --------------------------------------------------------------

let activeId = null;

export function activeSetId() {
  if (activeId) return activeId;
  try {
    activeId = getProfile().prefs.pieceSet || DEFAULT_SET;
  } catch {
    activeId = DEFAULT_SET;
  }
  return activeId;
}

export function setActiveSet(id) {
  activeId = setById(id).id;
  return activeId;
}

/** `#cburnett-wn` for the active set. */
export function pieceHref(colour, type) {
  return `#${activeSetId()}-${colour}${type}`;
}

/** Same, for an explicit set — used by the Settings previews. */
export function pieceHrefFor(setId, colour, type) {
  return `#${setById(setId).id}-${colour}${type}`;
}

// -- DOM ---------------------------------------------------------------------

let spritePromise = null;

/**
 * Injects the Pocket set immediately, then loads the bundled external sets.
 *
 * Awaited during boot so the default set is present for the first paint;
 * Pocket going in synchronously means a sprite fetch failure degrades to a
 * playable board rather than an empty one.
 */
export function installSprite(doc = document) {
  if (spritePromise) return spritePromise;

  if (!doc.getElementById('piece-sprite-pocket')) {
    const host = doc.createElement('div');
    host.id = 'piece-sprite-pocket';
    host.setAttribute('aria-hidden', 'true');
    host.innerHTML = pocketSprite();
    doc.body.prepend(host);
  }

  const url = new URL('../../assets/pieces.svg', import.meta.url).href;
  spritePromise = fetch(url)
    .then((res) => {
      if (!res.ok) throw new Error(`piece sprite: HTTP ${res.status}`);
      return res.text();
    })
    .then((svg) => {
      if (doc.getElementById('piece-sprite-external')) return true;
      const host = doc.createElement('div');
      host.id = 'piece-sprite-external';
      host.setAttribute('aria-hidden', 'true');
      host.innerHTML = svg;
      doc.body.prepend(host);
      return true;
    })
    .catch((err) => {
      // Fall back to Pocket rather than rendering an empty board.
      console.warn('Falling back to the Pocket piece set:', err.message);
      setActiveSet('pocket');
      return false;
    });

  return spritePromise;
}

/** An <svg><use> element for a chess.js piece ({ type, color }). */
export function pieceElement(piece, setId) {
  const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
  svg.setAttribute('class', 'piece');
  svg.setAttribute('viewBox', '0 0 45 45');
  svg.setAttribute('aria-hidden', 'true');
  const use = document.createElementNS('http://www.w3.org/2000/svg', 'use');
  // A <symbol> carries its own viewBox, so <use> scales each set's native
  // coordinate space (45, 72, 260, 800, 5871…) into this 45x45 viewport.
  use.setAttribute('href', setId
    ? pieceHrefFor(setId, piece.color, piece.type)
    : pieceHref(piece.color, piece.type));
  svg.appendChild(use);
  return svg;
}
